### PR TITLE
Fix some PHP 8 warnings

### LINKED ISSUE #459: The plugin causes an errors on PHP 8.1
I upgraded to Release 2022-07-31 “Igor” today. Then upgraded to PHP 8.1 and after reloading the page I got the following errors.
Only after disabling the plugin, all the errors disappear. 

Bildschirmfoto 2022-08-24 um 14 56 49

### PR DESCRIPTION
**Pull request by annda**
Should fix #459

### CODE REVIEW

File: action.php [hunk 1]
```diff
@@ -503,7 +503,7 @@ protected function generatePDF($cachefile, $event) {
         }
 
         // insert the back page
-        $body_end = $template['back'];
+        $body_end = $template['back'] ?? '';
```
Comment (Klap-in) [inline action.php:506]: In general it is nicer if variables are always defined, in stead of check if these exists.
In this case this variable is forgotten in the `load_template()` function. Could you add it please? Please check if there are more variables returned that are possible not defined.

Comment (annda) [reply action.php]: Thanks for pointing this out. I haven't found any other undefined variables and added just `back` to the list in `load_template()`.

I amended the commit.

**Comment by Klap-in** [comment]
Thanks for the improvements
